name: Format

on: [push]

jobs:
  format:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup node/npm
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Format project
        run: npm run format

      - name: Commit format updates
        uses: phated/git-auto-commit-action@v4
        with:
          commit_message: "chore: Fix formatting"
